site_name: IASI Code Collection
site_url: https://slcs-jsc.github.io/iasi/
repo_url: https://github.com/slcs-jsc/iasi
docs_dir: manual
theme: material

nav:
    - Home: index.md
    - Links: links.md
